// <auto-generated />
using System;
using BookingFlightServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingFlightServer.Migrations
{
    [DbContext(typeof(BookingFlightContext))]
    partial class BookingFlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingFlightServer.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__46A222CD16D48287");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("phone_number");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__43AA41410978B09D");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Admin__46A222CC24D6D9F3")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("airport_code");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("airport_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("city");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.HasKey("AirportId")
                        .HasName("PK__Airport__C795D5168D90093F");

                    b.HasIndex("ManagerId");

                    b.ToTable("Airport", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.AirportPrice", b =>
                {
                    b.Property<int>("AirportPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airport_price_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportPriceId"));

                    b.Property<int>("AirportFromId")
                        .HasColumnType("int")
                        .HasColumnName("airport_from_id");

                    b.Property<int>("AirportToId")
                        .HasColumnType("int")
                        .HasColumnName("airport_to_id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("base_price");

                    b.HasKey("AirportPriceId")
                        .HasName("PK__AirportP__E5C343471C893DA2");

                    b.HasIndex("AirportFromId");

                    b.HasIndex("AirportToId");

                    b.ToTable("AirportPrice", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.ClassSeat", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("class_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.HasKey("ClassId")
                        .HasName("PK__ClassSea__FDF479865214DBFF");

                    b.ToTable("ClassSeat", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complaint_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("ComplaintId")
                        .HasName("PK__Complain__A771F61CEAA299EB");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupporterId");

                    b.ToTable("Complaint", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("phone_number");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB8518A1C4A0");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Customer__46A222CC00BC4C29")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discount_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("discount_code");

                    b.Property<string>("DiscountInfor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_infor");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discount_percent");

                    b.Property<string>("DiscountTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("discount_title");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.HasKey("DiscountId")
                        .HasName("PK__Discount__BDBE9EF987994503");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "DiscountCode" }, "UQ__Discount__75C1F006A23F89FF")
                        .IsUnique();

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__7A6B2B8CD8086017");

                    b.HasIndex("AccountId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.FeedbackTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("TicketId");

                    b.ToTable("FeedbackTickets");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int")
                        .HasColumnName("arrival_airport_id");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_time");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int")
                        .HasColumnName("departure_airport_id");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_time");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("flight_code");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<int>("PlaneId")
                        .HasColumnType("int")
                        .HasColumnName("plane_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("tax");

                    b.HasKey("FlightId")
                        .HasName("PK__Flight__E3705765B435071C");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PlaneId");

                    b.HasIndex("StatusId");

                    b.ToTable("Flight", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.FlightSeat", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<bool>("IsSat")
                        .HasColumnType("bit")
                        .HasColumnName("isSat");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("FlightId", "SeatId");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketId");

                    b.ToTable("Flight_Seat", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Detail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("detail");

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("anh-bien.jpg")
                        .HasColumnName("image");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("ItemId")
                        .HasName("PK__Items__52020FDD275EA735");

                    b.HasIndex("StatusId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("phone_number");

                    b.HasKey("ManagerId")
                        .HasName("PK__Manager__5A6073FC44C27C13");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Manager__46A222CC0AB30127")
                        .IsUnique();

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.News", b =>
                {
                    b.Property<int>("NewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("new_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("NewId")
                        .HasName("PK__News__8215F58893AC1690");

                    b.HasIndex("AccountId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842FCF900CB8");

                    b.HasIndex("AccountId");

                    b.HasIndex("StatusId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__ED1FC9EA3B39579E");

                    b.HasIndex("StatusId");

                    b.HasIndex("TicketId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Plane", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plane_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaneId"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Manufacture")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manufacture");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("PlaneCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("plane_code");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("PlaneId")
                        .HasName("PK__Plane__4D11D7FDD690FD48");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Plane", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CC9AF58AE3");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int?>("PlaneId")
                        .HasColumnType("int")
                        .HasColumnName("plane_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("SeatId")
                        .HasName("PK__Seat__906DED9C118FEE73");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlaneId");

                    b.HasIndex("StatusId");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Detail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("detail");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("service_name");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__3E0DB8AFAC8D5893");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status_name");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("status_type")
                        .IsFixedLength();

                    b.HasKey("StatusId")
                        .HasName("PK__Status__3683B5310291BB56");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupporterId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("phone_number");

                    b.HasKey("SupporterId")
                        .HasName("PK__Supporte__F3A577016AD0363F");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Supporte__46A222CCCEC18A66")
                        .IsUnique();

                    b.ToTable("Supporter", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<int>("ClassSeatId")
                        .HasColumnType("int")
                        .HasColumnName("class_seat_id");

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_full_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("contact_phone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ticket_number");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("total_price");

                    b.HasKey("TicketId")
                        .HasName("PK__Ticket__D596F96BCC0A6FCE");

                    b.HasIndex("ClassSeatId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FlightId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "TicketNumber" }, "UQ__Ticket__413613D2A41FFAC9")
                        .IsUnique();

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.TicketItem", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("TicketId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Ticket_Item", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.UserLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("datetime")
                        .HasColumnName("access_time");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("detail");

                    b.HasKey("LogId")
                        .HasName("PK__User_Log__9E2397E09BCC7CA8");

                    b.HasIndex("AccountId");

                    b.ToTable("User_Logs", (string)null);
                });

            modelBuilder.Entity("FlightService", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.HasKey("FlightId", "ServiceId")
                        .HasName("PK__FlightSe__00908CEFF11099F1");

                    b.HasIndex("ServiceId");

                    b.ToTable("FlightService", (string)null);
                });

            modelBuilder.Entity("ServiceItem", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.HasKey("ServiceId", "ItemId")
                        .HasName("PK__Service___FB2D9852CD5AA2FD");

                    b.HasIndex("ItemId");

                    b.ToTable("Service_Item", (string)null);
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Account", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Account__role_id__07C12930");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Accounts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Account__status___08B54D69");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Admin", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("BookingFlightServer.Entities.Admin", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__account_i__09A971A2");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Airport", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Manager", "Manager")
                        .WithMany("Airports")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__Airport__manager__0A9D95DB");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.AirportPrice", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Airport", "AirportFrom")
                        .WithMany("AirportPriceAirportFroms")
                        .HasForeignKey("AirportFromId")
                        .IsRequired()
                        .HasConstraintName("FK__AirportPr__airpo__0B91BA14");

                    b.HasOne("BookingFlightServer.Entities.Airport", "AirportTo")
                        .WithMany("AirportPriceAirportTos")
                        .HasForeignKey("AirportToId")
                        .IsRequired()
                        .HasConstraintName("FK__AirportPr__airpo__0C85DE4D");

                    b.Navigation("AirportFrom");

                    b.Navigation("AirportTo");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Complaint", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Complaint__custo__0D7A0286");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Complaints")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Complaint__statu__0E6E26BF");

                    b.HasOne("BookingFlightServer.Entities.Supporter", "Supporter")
                        .WithMany("Complaints")
                        .HasForeignKey("SupporterId")
                        .IsRequired()
                        .HasConstraintName("FK__Complaint__suppo__0F624AF8");

                    b.Navigation("Customer");

                    b.Navigation("Status");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Customer", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("BookingFlightServer.Entities.Customer", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Customer__accoun__10566F31");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Discount", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Customer", "Customer")
                        .WithMany("Discounts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Discount__custom__114A936A");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Feedback", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__accoun__123EB7A3");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.FeedbackTicket", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingFlightServer.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Flight", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Airport", "ArrivalAirport")
                        .WithMany("FlightArrivalAirports")
                        .HasForeignKey("ArrivalAirportId")
                        .IsRequired()
                        .HasConstraintName("FK__Flight__arrival___123EB7A3");

                    b.HasOne("BookingFlightServer.Entities.Airport", "DepartureAirport")
                        .WithMany("FlightDepartureAirports")
                        .HasForeignKey("DepartureAirportId")
                        .IsRequired()
                        .HasConstraintName("FK__Flight__departur__14270015");

                    b.HasOne("BookingFlightServer.Entities.Manager", "Manager")
                        .WithMany("Flights")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__Flight__manager___151B244E");

                    b.HasOne("BookingFlightServer.Entities.Plane", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneId")
                        .IsRequired()
                        .HasConstraintName("FK__Flight__plane_id__160F4887");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Flights")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Flight__status_i__17036CC0");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");

                    b.Navigation("Manager");

                    b.Navigation("Plane");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.FlightSeat", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_Seat_Flight");

                    b.HasOne("BookingFlightServer.Entities.Seat", "Seat")
                        .WithMany("FlightSeats")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_Flight_Seat_Seat");

                    b.HasOne("BookingFlightServer.Entities.Ticket", "Ticket")
                        .WithMany("FlightSeats")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK_Flight_Seat_Ticket");

                    b.Navigation("Flight");

                    b.Navigation("Seat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Item", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Items")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Items_Status");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Manager", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithOne("Manager")
                        .HasForeignKey("BookingFlightServer.Entities.Manager", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Manager__account__1DB06A4F");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.News", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithMany("News")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__News__account_id__1EA48E88");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Notification", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__accou__1F98B2C1");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__statu__208CD6FA");

                    b.Navigation("Account");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Payment", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__status___2180FB33");

                    b.HasOne("BookingFlightServer.Entities.Ticket", "Ticket")
                        .WithMany("Payments")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__ticket___1EA48E88");

                    b.Navigation("Status");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Plane", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Manager", "Manager")
                        .WithMany("Planes")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__Plane__manager_i__236943A5");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Planes")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Plane__status_id__245D67DE");

                    b.Navigation("Manager");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Seat", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.ClassSeat", "Class")
                        .WithMany("Seats")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Seat__class_id__2180FB33");

                    b.HasOne("BookingFlightServer.Entities.Plane", "Plane")
                        .WithMany("Seats")
                        .HasForeignKey("PlaneId")
                        .HasConstraintName("FK_Seat_Plane");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Seats")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Seat__status_id__22751F6C");

                    b.Navigation("Class");

                    b.Navigation("Plane");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Service", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Manager", "Manager")
                        .WithMany("Services")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__Service__manager__282DF8C2");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Services")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Service_Status");

                    b.Navigation("Manager");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Supporter", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithOne("Supporter")
                        .HasForeignKey("BookingFlightServer.Entities.Supporter", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Supporter__accou__2BFE89A6");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Ticket", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.ClassSeat", "ClassSeat")
                        .WithMany("Tickets")
                        .HasForeignKey("ClassSeatId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_ClassSeat");

                    b.HasOne("BookingFlightServer.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Ticket__customer__2B0A656D");

                    b.HasOne("BookingFlightServer.Entities.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK__Ticket__flight_i__2BFE89A6");

                    b.HasOne("BookingFlightServer.Entities.Status", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Ticket__status_i__2CF2ADDF");

                    b.Navigation("ClassSeat");

                    b.Navigation("Customer");

                    b.Navigation("Flight");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.TicketItem", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Item", "Item")
                        .WithMany("TicketItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Item_Items");

                    b.HasOne("BookingFlightServer.Entities.Ticket", "Ticket")
                        .WithMany("TicketItems")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Item_Ticket");

                    b.Navigation("Item");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.UserLog", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Account", "Account")
                        .WithMany("UserLogs")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__User_Logs__accou__32AB8735");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FlightService", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK__FlightSer__fligh__1AD3FDA4");

                    b.HasOne("BookingFlightServer.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__FlightSer__servi__1BC821DD");
                });

            modelBuilder.Entity("ServiceItem", b =>
                {
                    b.HasOne("BookingFlightServer.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Service_I__item___2A164134");

                    b.HasOne("BookingFlightServer.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Service_I__servi__2B0A656D");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Account", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Feedbacks");

                    b.Navigation("Manager");

                    b.Navigation("News");

                    b.Navigation("Notifications");

                    b.Navigation("Supporter");

                    b.Navigation("UserLogs");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Airport", b =>
                {
                    b.Navigation("AirportPriceAirportFroms");

                    b.Navigation("AirportPriceAirportTos");

                    b.Navigation("FlightArrivalAirports");

                    b.Navigation("FlightDepartureAirports");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.ClassSeat", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Customer", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Discounts");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Flight", b =>
                {
                    b.Navigation("FlightSeats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Item", b =>
                {
                    b.Navigation("TicketItems");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Manager", b =>
                {
                    b.Navigation("Airports");

                    b.Navigation("Flights");

                    b.Navigation("Planes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Plane", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Seat", b =>
                {
                    b.Navigation("FlightSeats");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Status", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Complaints");

                    b.Navigation("Flights");

                    b.Navigation("Items");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Planes");

                    b.Navigation("Seats");

                    b.Navigation("Services");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Supporter", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("BookingFlightServer.Entities.Ticket", b =>
                {
                    b.Navigation("FlightSeats");

                    b.Navigation("Payments");

                    b.Navigation("TicketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
